version: '3.4'

services:
  database:
    image: mariadb:11.3.2
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: CompleteDeveloperNetwork
    networks:
      - api-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - "8080:8080"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Connection=server=database;port=3306;database=CompleteDeveloperNetwork;user=root;password=my-secret-pw;"
    networks:
      - api-network

volumes:
  datafiles:

networks:
  api-network:
    driver: bridge
